### ISSUE TITLE
ERROR: www-client/cyberfox-9999::cyberfox-overlay failed (depend phase)

### ISSUE THREAD

**Issue by T0MuX** [logicoftekk/Cyberfox-Overlay#1]
Hi people !

I'm having an issue on merging cyberfox-overlay.
I did, in the order, the following :
- Edit layman.cfg to add the repository `sudo nano /etc/layman/layman.cfg`
- Did a `sudo layman -L` to check if cyberfox is available and yes it is
- Add cyberfox-overlay to layman `sudo layman -a cyberfox-overlay`
- Merging Cyberfox `sudo emerge -a cyberfox-overlay`
  And then I have this issue : 

> t0mux@tomux-pc ~ $ sudo emerge -a www-client/cyberfox
> - IMPORTANT: 1 news items need reading for repository 'gentoo'.
> - Use eselect news read to view new items.
> 
> These are the packages that would be merged, in order:
> 
> Calculating dependencies | \* ERROR: www-client/cyberfox-9999::cyberfox-overlay failed (depend phase):
> -   mozconfig-v6.47.eclass could not be found by inherit()
> - 
> - Call stack:
> -              ebuild.sh, line 624:  Called source '/var/lib/layman/cyberfox-overlay/www-client/cyberfox/cyberfox-9999.ebuild'
> -   cyberfox-9999.ebuild, line  14:  Called inherit 'check-reqs' 'flag-o-matic' 'toolchain-funcs' 'eutils' 'gnome2-utils' 'mozconfig-v6.47' 'multilib' 'pax-utils' 'fdo-mime' 'autotools' 'virtualx' 'git-r3'
> -              ebuild.sh, line 297:  Called die
> - The specific snippet of code:
> -              [[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
> - 
> - If you need support, post the output of `emerge --info '=www-client/cyberfox-9999::cyberfox-overlay'`,
> - the complete build log and the output of `emerge -pqv '=www-client/cyberfox-9999::cyberfox-overlay'`.
> - Working directory: '/usr/lib64/python3.4/site-packages'
> - S: '/var/tmp/portage/www-client/cyberfox-9999/work/cyberfox-9999'
>   ... done!
> 
> !!! All ebuilds that could satisfy "www-client/cyberfox" have been masked.
> !!! One of the following masked packages is required to complete your request:
> - www-client/cyberfox-9999::cyberfox-overlay (masked by: corruption)
> 
> For more information, see the MASKED PACKAGES section in the emerge
> man page or refer to the Gentoo Handbook.

I thank you by advance for helping me. Bye !

**Comment by logicoftekk** [comment]
ah looks like mozconfig moved to v6.48 ill update the ebuilds later today along with the latest patch set

**Comment by logicoftekk** [comment]
Updated cyberfox-9999.ebuild

**Comment by T0MuX** [comment]
Great yeah ! I'm merging cyberfox without any issue ! Thank you a lot :)
